project:
  type: website
  resources: assets
  output-dir: docs

website:
  title: "JACK Arena"
  navbar:
    left:
      - text: Team JACK
        href: index.qmd
      - text: Doppelkopf
        menu:
          - text: 2025 Season
            href: doppelkopf/2025.qmd
          - text: 2024 Season
            href: doppelkopf/2024.qmd
          - text: 2023 Season
            href: doppelkopf/2023.qmd
          - text: 2022 Season
            href: doppelkopf/2022.qmd
          - text: "---"
          - text: All Time Stats
            href: doppelkopf/all-time-stats.qmd
          - text: Seating
            href: doppelkopf/seating.qmd
      - text: Decathlon


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
